spring.application.name=coupon-api
spring.h2.console.enabled=true

# Fixar o nome do banco de dados para não mudar a cada restart
spring.datasource.url=jdbc:h2:mem:coupondb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuração do JPA/Hibernate para criar a tabela automaticamente
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true